/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package oracleconection;

/**
 *
 * @author JP
 */
public class menuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form menuUsuario
     */
    public menuUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MENÚ = new javax.swing.JPanel();
        menuTitulo = new javax.swing.JLabel();
        menuTexto = new javax.swing.JLabel();
        menuIngresarArtista = new javax.swing.JButton();
        menuIngresarDisco = new javax.swing.JButton();
        menuIngresarCanciones = new javax.swing.JButton();
        menuEditarMusica = new javax.swing.JButton();
        menuExplorar = new javax.swing.JButton();
        menuRankings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuTitulo.setText("Bienvenido a la Red Social de Musica!");

        menuTexto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuTexto.setText("Elija lo que quiera hacer:");

        menuIngresarArtista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuIngresarArtista.setText("Ingresar Artista");
        menuIngresarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarArtistaActionPerformed(evt);
            }
        });

        menuIngresarDisco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuIngresarDisco.setText("Ingresar Disco");
        menuIngresarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarDiscoActionPerformed(evt);
            }
        });

        menuIngresarCanciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuIngresarCanciones.setText("Ingresar Canciones");
        menuIngresarCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarCancionesActionPerformed(evt);
            }
        });

        menuEditarMusica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuEditarMusica.setText("Editar mi musica");
        menuEditarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarMusicaActionPerformed(evt);
            }
        });

        menuExplorar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuExplorar.setText("Explorar");
        menuExplorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExplorarActionPerformed(evt);
            }
        });

        menuRankings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuRankings.setText("Rankings");

        javax.swing.GroupLayout MENÚLayout = new javax.swing.GroupLayout(MENÚ);
        MENÚ.setLayout(MENÚLayout);
        MENÚLayout.setHorizontalGroup(
            MENÚLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENÚLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(MENÚLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(menuTitulo)
                    .addComponent(menuTexto)
                    .addComponent(menuIngresarArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuIngresarDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuIngresarCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuEditarMusica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuExplorar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuRankings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        MENÚLayout.setVerticalGroup(
            MENÚLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENÚLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(menuTitulo)
                .addGap(15, 15, 15)
                .addComponent(menuTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuIngresarArtista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuIngresarDisco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuIngresarCanciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuEditarMusica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuExplorar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuRankings)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(MENÚ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MENÚ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIngresarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarDiscoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        pantallaElegirArtista pElegirArtista = new pantallaElegirArtista();
        pElegirArtista.setVisible(true);
        pElegirArtista.pack();
        dispose();
    }//GEN-LAST:event_menuIngresarDiscoActionPerformed

    private void menuIngresarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarArtistaActionPerformed
        // TODO add your handling code here:
        pantallaInicio.SesionActual.getLogin();
        this.setVisible(false);
        pantallaIngresarArtista pIngresarArtista = new pantallaIngresarArtista();
        pIngresarArtista.setVisible(true);
        pIngresarArtista.pack();
        dispose();
    }//GEN-LAST:event_menuIngresarArtistaActionPerformed

    private void menuIngresarCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarCancionesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        pantallaElegirArtistaCaso4 pElegirArtistaCaso4 = new pantallaElegirArtistaCaso4();
        pElegirArtistaCaso4.setVisible(true);
        pElegirArtistaCaso4.pack();
        dispose();
    }//GEN-LAST:event_menuIngresarCancionesActionPerformed

    private void menuEditarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarMusicaActionPerformed
        this.setVisible(false);
        pantallaEditar pEditar = new pantallaEditar();
        pEditar.setVisible(true);
        pEditar.pack();
        dispose();
    }//GEN-LAST:event_menuEditarMusicaActionPerformed

    private void menuExplorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExplorarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        pantallaExplorar pExplorar = new pantallaExplorar();
        pExplorar.setVisible(true);
        pExplorar.pack();
        dispose();
    }//GEN-LAST:event_menuExplorarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MENÚ;
    private javax.swing.JButton menuEditarMusica;
    private javax.swing.JButton menuExplorar;
    private javax.swing.JButton menuIngresarArtista;
    private javax.swing.JButton menuIngresarCanciones;
    private javax.swing.JButton menuIngresarDisco;
    private javax.swing.JButton menuRankings;
    private javax.swing.JLabel menuTexto;
    private javax.swing.JLabel menuTitulo;
    // End of variables declaration//GEN-END:variables
}
