/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package oracleconection;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JP
 */
public class pantallaElegirArtistaCaso4 extends javax.swing.JFrame {
    
    static Connection conn=null;
    /**
     * Creates new form pantallaElegirArtistaCaso4
     */
    public pantallaElegirArtistaCaso4() {
        initComponents();
    }

public class funcionalidad { 
        private Connection conexion; 

        public Connection getConexion() { 
            return conexion; 
        }    public void setConexion(Connection conexion) { 
            this.conexion = conexion; 
        }  



public funcionalidad conectar() { 
    try { 
        Class.forName("oracle.jdbc.OracleDriver"); 
        String BaseDeDatos = "jdbc:oracle:thin:@localhost:1521:XE"; 
          
        conexion = DriverManager.getConnection(BaseDeDatos, "TAREA1BD","marti");             
        if (conexion != null) { 
            System.out.println("Conexion exitosa!"); 
        } else { 
            System.out.println("Conexion fallida!"); 
        } 
    } catch (Exception e) { 
        e.printStackTrace(); 
    }        return this; 
} 

public boolean escribir(String sql) { 
        try { 
            Statement sentencia; 
            sentencia = getConexion().createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY); 
            sentencia.executeUpdate(sql); 
            getConexion().commit(); 
            sentencia.close(); 
             
        } catch (SQLException e) { 
            e.printStackTrace(); 
            System.out.print("ERROR SQL"); 
            return false; 
        }         
        return true; 
    } 

public ResultSet consultar(String sql) { 
        ResultSet resultado = null; 
        try { 
            Statement sentencia; 
            sentencia = getConexion().createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY); 
            resultado = sentencia.executeQuery(sql); 
             
        } catch (SQLException e) { 
            e.printStackTrace(); 
            return null; 
        }        return resultado; 
    } 

    }    


private DefaultListModel llenarListaCaso4(){
     
    DefaultListModel<String> model = new DefaultListModel<>();
    
    try {
                                
            funcionalidad fUsuario = new funcionalidad();
            fUsuario.conectar(); 
            ResultSet idUsuario = fUsuario.consultar("select idusuario from usuario where login='"+pantallaInicio.SesionActual.login+"'");
            idUsuario.next();
            
            ResultSet idArtistasSeguidos = fUsuario.consultar("select artista_idartista from sigue where usuario_idusuario='"+idUsuario.getString(1)+"'");
            idUsuario.close();
            
            while(idArtistasSeguidos.next()){
                
                ResultSet nombreArtista = fUsuario.consultar("select nombre from artista where idartista='"+idArtistasSeguidos.getString(1)+"'");
                nombreArtista.next();
                model.addElement(nombreArtista.getString(1));
                nombreArtista.close();
                                           
            }
            idArtistasSeguidos.close();
                                   
        }catch (Exception e){
            System.out.println(e.getCause());
            JOptionPane.showMessageDialog(this,"Problemas con la consulta!");
        }
   return model;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ARTISTASSEGUIDOSCASO4 = new javax.swing.JPanel();
        artistaTitulo = new javax.swing.JLabel();
        botonMostrarArtistas = new javax.swing.JButton();
        pantallaResultados = new javax.swing.JScrollPane();
        artistasEncontradosCaso4 = new javax.swing.JList();
        botonSeleccionarArtista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        artistaTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        artistaTitulo.setText("Elegir Artista para elegir un Disco:");

        botonMostrarArtistas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonMostrarArtistas.setText("Mostrar Artistas Seguidos");
        botonMostrarArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarArtistasActionPerformed(evt);
            }
        });

        pantallaResultados.setViewportView(artistasEncontradosCaso4);

        botonSeleccionarArtista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonSeleccionarArtista.setText("Seleccionar Artista");
        botonSeleccionarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarArtistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ARTISTASSEGUIDOSCASO4Layout = new javax.swing.GroupLayout(ARTISTASSEGUIDOSCASO4);
        ARTISTASSEGUIDOSCASO4.setLayout(ARTISTASSEGUIDOSCASO4Layout);
        ARTISTASSEGUIDOSCASO4Layout.setHorizontalGroup(
            ARTISTASSEGUIDOSCASO4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTISTASSEGUIDOSCASO4Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(ARTISTASSEGUIDOSCASO4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonSeleccionarArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ARTISTASSEGUIDOSCASO4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pantallaResultados)
                        .addComponent(botonMostrarArtistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(artistaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        ARTISTASSEGUIDOSCASO4Layout.setVerticalGroup(
            ARTISTASSEGUIDOSCASO4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTISTASSEGUIDOSCASO4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(artistaTitulo)
                .addGap(18, 18, 18)
                .addComponent(botonMostrarArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pantallaResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSeleccionarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ARTISTASSEGUIDOSCASO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ARTISTASSEGUIDOSCASO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static artistaActual artistaSeleccionadoCaso4 = new artistaActual();
    
    private void botonMostrarArtistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarArtistasActionPerformed
        // TODO add your handling code here:
        artistasEncontradosCaso4.setModel(llenarListaCaso4());
    }//GEN-LAST:event_botonMostrarArtistasActionPerformed

    private void botonSeleccionarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarArtistaActionPerformed
        // TODO add your handling code here:
        artistaSeleccionadoCaso4.nombre = artistasEncontradosCaso4.getSelectedValue().toString();
        artistaSeleccionadoCaso4.nacionalidad = null;
        this.setVisible(false);
        pantallaElegirDisco pElegirDisco = new pantallaElegirDisco();
        pElegirDisco.setVisible(true);
        pElegirDisco.pack();
        dispose();
    }//GEN-LAST:event_botonSeleccionarArtistaActionPerformed
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaElegirArtistaCaso4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaElegirArtistaCaso4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaElegirArtistaCaso4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaElegirArtistaCaso4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaElegirArtistaCaso4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ARTISTASSEGUIDOSCASO4;
    private javax.swing.JLabel artistaTitulo;
    private javax.swing.JList artistasEncontradosCaso4;
    private javax.swing.JButton botonMostrarArtistas;
    private javax.swing.JButton botonSeleccionarArtista;
    private javax.swing.JScrollPane pantallaResultados;
    // End of variables declaration//GEN-END:variables
}
