/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package oracleconection;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author JP
 */
public class pantallaIngresarCancion extends javax.swing.JFrame {
    
    static Connection conn=null;
    
    /**
     * Creates new form pantallaIngresarCancion
     */
    public pantallaIngresarCancion() {
        initComponents();
    }

public class funcionalidad { 
        private Connection conexion; 

        public Connection getConexion() { 
            return conexion; 
        }    public void setConexion(Connection conexion) { 
            this.conexion = conexion; 
        }  



public funcionalidad conectar() { 
    try { 
        Class.forName("oracle.jdbc.OracleDriver"); 
        String BaseDeDatos = "jdbc:oracle:thin:@localhost:1521:XE"; 
          
        conexion = DriverManager.getConnection(BaseDeDatos, "TAREA1BD","marti");             
        if (conexion != null) { 
            System.out.println("Conexion exitosa!"); 
        } else { 
            System.out.println("Conexion fallida!"); 
        } 
    } catch (Exception e) { 
        e.printStackTrace(); 
    }        return this; 
} 

public boolean escribir(String sql) { 
        try { 
            Statement sentencia; 
            sentencia = getConexion().createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY); 
            sentencia.executeUpdate(sql); 
            getConexion().commit(); 
            sentencia.close(); 
             
        } catch (SQLException e) { 
            e.printStackTrace(); 
            System.out.print("ERROR SQL"); 
            return false; 
        }         
        return true; 
    } 

public ResultSet consultar(String sql) { 
        ResultSet resultado = null; 
        try { 
            Statement sentencia; 
            sentencia = getConexion().createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY); 
            resultado = sentencia.executeQuery(sql); 
             
        } catch (SQLException e) { 
            e.printStackTrace(); 
            return null; 
        }        return resultado; 
    } 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CANCION = new javax.swing.JPanel();
        cancionTitulo = new javax.swing.JLabel();
        canciontNombre = new javax.swing.JLabel();
        canciontDuracion = new javax.swing.JLabel();
        canciontNumeroPista = new javax.swing.JLabel();
        canciontLink = new javax.swing.JLabel();
        cancionNombre = new javax.swing.JTextField();
        cancionDuracion = new javax.swing.JTextField();
        cancionNumeroPista = new javax.swing.JTextField();
        cancionLink = new javax.swing.JTextField();
        canciontAviso = new javax.swing.JLabel();
        cancionBotonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cancionTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancionTitulo.setText("Datos de la Canción:");

        canciontNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canciontNombre.setText("Nombre de la Canción:");

        canciontDuracion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canciontDuracion.setText("Duración:");

        canciontNumeroPista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canciontNumeroPista.setText("Número de pista:");

        canciontLink.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canciontLink.setText("Link para escuchar:");

        cancionNumeroPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancionNumeroPistaActionPerformed(evt);
            }
        });

        canciontAviso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        canciontAviso.setText("(Link puede ser de youtube/vimeo o spotify/grooveshark)");

        cancionBotonAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancionBotonAceptar.setText("Aceptar");
        cancionBotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancionBotonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CANCIONLayout = new javax.swing.GroupLayout(CANCION);
        CANCION.setLayout(CANCIONLayout);
        CANCIONLayout.setHorizontalGroup(
            CANCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CANCIONLayout.createSequentialGroup()
                .addGroup(CANCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CANCIONLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(cancionTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CANCIONLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(CANCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(canciontAviso)
                            .addGroup(CANCIONLayout.createSequentialGroup()
                                .addGroup(CANCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(canciontDuracion)
                                    .addComponent(canciontNombre)
                                    .addComponent(canciontNumeroPista)
                                    .addComponent(canciontLink))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(CANCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cancionNombre)
                                    .addComponent(cancionDuracion)
                                    .addComponent(cancionNumeroPista)
                                    .addComponent(cancionLink, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))))
                    .addGroup(CANCIONLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(cancionBotonAceptar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        CANCIONLayout.setVerticalGroup(
            CANCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CANCIONLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancionTitulo)
                .addGap(30, 30, 30)
                .addGroup(CANCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canciontNombre)
                    .addComponent(cancionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CANCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canciontDuracion)
                    .addComponent(cancionDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CANCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canciontNumeroPista)
                    .addComponent(cancionNumeroPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CANCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canciontLink)
                    .addComponent(cancionLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(canciontAviso)
                .addGap(29, 29, 29)
                .addComponent(cancionBotonAceptar)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CANCION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CANCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancionNumeroPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancionNumeroPistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancionNumeroPistaActionPerformed

    private void cancionBotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancionBotonAceptarActionPerformed
        // TODO add your handling code here:
        try{
            
            funcionalidad fCancion = new funcionalidad(); 
            fCancion.conectar();
            ResultSet idDisco = fCancion.consultar("select iddisco from disco where nombre='"+pantallaElegirDisco.discoSeleccionado.nombre+"'");
            idDisco.next();
                                    
            conn = Main.Enlace(conn);
            String sqlinsertar = "insert into canción values (?,?,?,?,?,?,?)";
            PreparedStatement insercion = conn.prepareStatement(sqlinsertar);
            insercion.setString(1, null);
            insercion.setString(2, idDisco.getString(1));
            insercion.setString(3, cancionNombre.getText());
            insercion.setString(4, cancionDuracion.getText());
            insercion.setString(5, cancionNumeroPista.getText());
            insercion.setString(6, cancionLink.getText());
            insercion.setString(7, "0");
            insercion.execute();
            insercion.close();
            
            JOptionPane.showMessageDialog(this,"Cancion ingresada con exito!");
        
        
        }catch(Exception e){
            System.out.println(e.getCause());
            JOptionPane.showMessageDialog(this,"La canción ya existe en el disco, porfavor corrija nombre y numero de pista!");
        }
    }//GEN-LAST:event_cancionBotonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaIngresarCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaIngresarCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaIngresarCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaIngresarCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaIngresarCancion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CANCION;
    private javax.swing.JButton cancionBotonAceptar;
    private javax.swing.JTextField cancionDuracion;
    private javax.swing.JTextField cancionLink;
    private javax.swing.JTextField cancionNombre;
    private javax.swing.JTextField cancionNumeroPista;
    private javax.swing.JLabel cancionTitulo;
    private javax.swing.JLabel canciontAviso;
    private javax.swing.JLabel canciontDuracion;
    private javax.swing.JLabel canciontLink;
    private javax.swing.JLabel canciontNombre;
    private javax.swing.JLabel canciontNumeroPista;
    // End of variables declaration//GEN-END:variables
}
